export const SET_ALL_PRODUCTS = 'SET_ALL_PRODUCTS';
export const ALTER_SORT_FILTER = 'ALTER_SORT_FILTER';
export const SET_ALL_FILTERS = 'SET_ALL_FILTERS';
export const ALTER_FILTER_DATA = 'ALTER_FILTER_DATA';
